### ISSUE TITLE
Bug with folders

### ISSUE THREAD

**Issue by litmleong** [lithiumtech/yum-s3-repo-manager#2]
The key.get_contents_to_filename(localFileName) command in the downloadKeys function would crash under the following situation:

- install cyberduck (available on Windows and Mac)
- browse to your bucket/inbox
- right click, create a folder

On the next pull, it would crash w/ the following error:
````
ERROR:apscheduler.scheduler:Job "manageYumRepo (trigger: interval[0:01:00], next run at: 2014-10-28 20:29:39.390200)" raised an exception
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/apscheduler/scheduler.py", line 510, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/opt/yum-repo-manager.py", line 301, in manageYumRepo
    skippedKeys = downloadKeys(inboxKeys, options.localStagingArea + "/" + options.repoFolderName, options.inboxFolderName + "/")
  File "/opt/yum-repo-manager.py", line 186, in downloadKeys
    key.get_contents_to_filename(localFileName)
  File "/usr/lib/python2.6/site-packages/boto/s3/key.py", line 1707, in get_contents_to_filename
    os.remove(filename)
OSError: [Errno 21] Is a directory: '/repostaging/repo/mleong/test/'
`````

It thinks the folder created by cyberduck is a file.

The instance was created on 10/28/14 via cloudformation, using the latest version of boto.

If I create the folder via Amazon's webui, that error doesn't exist.

**Comment by matthewbogner** [comment]
this was fixed by #4
